apiVersion: v1
kind: Service
metadata:
  name: go-http-server
  labels:
    app: go-http-server
spec:
  type: NodePort
  selector:
    app: go-http-server
  ports:
  - name: http
    protocol: TCP
    port: 8080        # Service port
    targetPort: 8080  # Container port
    nodePort: 30080   # External port (accessible via minikube IP)
  sessionAffinity: None

# Made with Bob
